apiVersion: v1
kind: Service
metadata:
  name: golang-template
  labels:
    name: golang-template
    role: http
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: http
  selector:
    name: golang-template
    role: http
