apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-template-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: golang-template-worker
  template:
    metadata:
      labels:
        app: golang-template-worker
    spec:
      containers:
        - name: golang-template-worker
          image: GOLANG_TEMPLATE_IMAGE
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 40
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 40
            periodSeconds: 20
          resources:
            limits:
              memory: 2048Mi
              cpu: 500m
            requests:
              memory: 1024Mi
              cpu: 300m