APP_NAME: "Golang Template👋"
APP_PORT: 9090
MONGO_URI: 'mongodb://localhost:27017/golang-template'

KAFKA_BOOTSTRAP_SERVERS: 'localhost:9092'
KAFKA_GROUP_ID: 'golang-template'
KAFKA_AUTO_OFFSET_RESET: 'earliest'